spring.application.name=api_carrinho
# Configura o Jackson para formatar a sa�da JSON de forma leg�vel
spring.jackson.serialization.indent-output=true

# URL de conex�o com o banco de dados MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/carrinho_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=admin

# Configura��es do Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
